### PR TITLE
Attempt to fix it not being gcsafe

### PR DESCRIPTION
**Pull request by lost-rob0t**
This is my First PR, please Correct anything that is wrong here.

I noticed when i was trying to use it with Prologue web framework that nim was complaining that it was not gc safe?
I found adding that flag had nim stop complaining about it.

### CODE REVIEW

**Comment by hamidb80** [comment]
Hey,
Does library still work today? 

I thought it's broken since it uses some deleted functions in package `macroplus`

It definitely needs cleanup

**Comment by lost-rob0t** [comment]
Yup it works, Didn't even know about the changes.
Im not sure about the queryserver, I havent tried that.
But the normal CRUD Does work.

**Comment by hamidb80** [comment]
Thanks for pull request, I will make a new release when I tested it

**Comment by hamidb80** [comment]
what I really wanna do is to make APIs type-checked like what I did in my [Bale bot API](https://github.com/hamidb80/bale)

I marked all of the responses as `distinct JsonNode`

**Comment by hamidb80** [comment]
I've tested it on CouchDB `v3.3.2` (because couldn't find 3.1.1 binary for Windows).
`_update` and `node_config` API's does not work, anything else has no problem.

happy coding!

**Pull request merged**
